# -*- coding: utf-8 -*-
"""db_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkOYFYiRVdQ0GXLaDapg-aqLf4TJT_ms

import libraries
"""

import sqlite3

"""Database manager class"""

class DatabaseManager:
    def __init__(self, db_name="papers.db"):
        self.db_name = db_name
        self._create_table()

    def _get_connection(self):
        return sqlite3.connect(self.db_name)

    def _create_table(self):
        conn = self._get_connection()
        cursor = conn.cursor()
        cursor.execute(
            "CREATE TABLE IF NOT EXISTS papers ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "title TEXT, "
            "authors TEXT, "
            "published_date TEXT, "
            "abstract TEXT, "
            "url TEXT, "
            "source TEXT, "
            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
        )
        conn.commit()
        conn.close()

    def save_papers(self, papers, source_name):
        conn = self._get_connection()
        cursor = conn.cursor()
        for p in papers:
            authors_str = ", ".join(p.get("authors", []))
            cursor.execute(
                "INSERT INTO papers (title, authors, published_date, abstract, url, source) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (
                    p.get("title"),
                    authors_str,
                    p.get("published_date"),
                    p.get("abstract"),
                    p.get("url"),
                    source_name,
                ),
            )
        conn.commit()
        conn.close()