# -*- coding: utf-8 -*-
"""fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uz1gmmUDvJ-KY0RV7YU9VReuk4Vgg98Q

"""

# import libraries
import xml.etree.ElementTree as ET
import requests

"""SemanticScholarFetcher"""

class SemanticScholarFetcher:
    def fetch(self, query, limit=5):
        url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={query}&limit={limit}&fields=title,abstract,authors,year,url"
        response = requests.get(url)
        papers = []
        if response.status_code == 200:
            data = response.json().get("data", [])
            for item in data:
                authors = [
                    a["name"]
                    for a in item.get("authors", [])
                    if "name" in a
                ]
                papers.append(
                    {
                        "title": item.get("title"),
                        "authors": authors,
                        "published_date": str(item.get("year", "Unknown")),
                        "abstract": item.get("abstract", ""),
                        "url": item.get("url"),
                    }
                )
        return papers

"""ArxivFetcher"""

class ArxivFetcher:
    def fetch(self, query, limit=5):
        url = f"http://export.arxiv.org/api/query?search_query=all:{query}&start=0&max_results={limit}"
        response = requests.get(url)
        papers = []
        if response.status_code == 200:
            root = ET.fromstring(response.content)
            ns = {
                "atom": "http://www.w3.org/2005/Atom",
                "arxiv": "http://arxiv.org/schemas/atom",
            }
            for entry in root.findall("atom:entry", ns):
                title = entry.find("atom:title", ns).text.strip()
                summary = entry.find("atom:summary", ns).text.strip()
                url_id = entry.find("atom:id", ns).text
                published = entry.find("atom:published", ns).text[:10]
                authors = [
                    a.find("atom:name", ns).text
                    for a in entry.findall("atom:author", ns)
                ]
                papers.append(
                    {
                        "title": title,
                        "authors": authors,
                        "published_date": published,
                        "abstract": summary,
                        "url": url_id,
                    }
                )
        return papers

"""CrossrefFetcher"""

class CrossrefFetcher:
    def fetch(self, query, limit=5):
        url = f"https://api.crossref.org/works?query={query}&rows={limit}"
        headers = {
            "User-Agent": "ResearchScript/1.0 (mailto:your_email@example.com)"
        }
        response = requests.get(url, headers=headers)
        papers = []
        if response.status_code == 200:
            items = response.json().get("message", {}).get("items", [])
            for item in items:
                titles = item.get("title", ["Untitled"])
                title = titles[0] if len(titles) > 0 else "Untitled"
                authors = []
                for a in item.get("author", []):
                    first = a.get("given", "")
                    last = a.get("family", "")
                    name = f"{first} {last}".strip()
                    if name:
                        authors.append(name)
                created_date = item.get("created", {}).get(
                    "date-parts", [[None]]
                )[0]
                published_date = (
                    "-".join(map(str, created_date))
                    if created_date[0] is not None
                    else "Unknown"
                )
                doi = item.get("DOI")
                paper_url = f"https://doi.org/{doi}" if doi else ""
                papers.append(
                    {
                        "title": title,
                        "authors": authors,
                        "published_date": published_date,
                        "abstract": item.get("abstract", ""),
                        "url": paper_url,
                    }
                )
        return papers