# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9AOatuefsSAVUoGBpzTlufFvRpj0x5W
"""

# import libraries

from db_manager import DatabaseManager
from fetcher import ArxivFetcher, CrossrefFetcher, SemanticScholarFetcher


class PaperService:
    def __init__(self, db_manager):
        self.db_manager = db_manager
        self.fetchers = {
            "Semantic Scholar": SemanticScholarFetcher(),
            "arXiv": ArxivFetcher(),
            "CrossRef": CrossrefFetcher(),
        }

    def fetch_and_save_all(self, query, limit_per_source=5):
        total_count = 0

        for source_name, fetcher in self.fetchers.items():
            papers = fetcher.fetch(query, limit_per_source)
            self.db_manager.save_papers(papers, source_name)
            total_count += len(papers)

        return total_count


if __name__ == "__main__":
    db = DatabaseManager("papers.db")
    service = PaperService(db)

    total = service.fetch_and_save_all(
        query="Machine Learning",
        limit_per_source=3,
    )